# Generated by Django 4.1.4 on 2022-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.SmallIntegerField()),
                ("price", models.IntegerField()),
                ("mileage", models.IntegerField()),
                ("state_number", models.CharField(max_length=30, null=True)),
                ("href", models.CharField(max_length=300)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
